get_filename_component(_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set (TinyXML2_INCLUDE_DIRS "${_PREFIX}/include")
set (TinyXML2_INCLUDE_DIR "${TinyXML_INCLUDE_DIRS}")
set (TinyXML2_LIBRARIES debug "${_PREFIX}/lib/tinyxml2d.lib" optimized "${_PREFIX}/lib/tinyxml2.lib")
set (TinyXML2_LIBRARY "${TinyXML_LIBRARIES}")
